#!/usr/bin/env python3
"""
v2.42+ post-render jargon filter for phantom-modes outputs.

Reads `.skills/_jargon_bank.json` (generated by `build-manifest.py` from
`docs/system/operator-vocabulary-translation.md`) and substitutes internal
jargon tokens with operator-facing vocabulary in any input text.

Substitution policy:
- case-insensitive match on each `internal` variant
- preserves original case skeleton when possible (Atlas Vivant -> Historique...)
- skips content inside code blocks (``` fenced or `inline`)
- preserves markdown structure (headers, lists, table pipes, blockquotes)
- context filter: only entries tagged `phantom-modes` apply by default

Usage:
    # stdin -> stdout (default locale FR)
    cat output.md | python3 .skills/apply-jargon-filter.py

    # explicit locale EN
    cat output.md | python3 .skills/apply-jargon-filter.py --locale en

    # file in/out
    python3 .skills/apply-jargon-filter.py --in output.md --out filtered.md

    # programmatic
    from apply_jargon_filter import apply_jargon_filter
    filtered = apply_jargon_filter(text, locale="fr")
"""

import argparse
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
JARGON_BANK = SCRIPT_DIR / "_jargon_bank.json"

CODE_FENCE_RE = re.compile(r"(```.*?```)", re.DOTALL)
INLINE_CODE_RE = re.compile(r"(`[^`\n]+`)")


def _load_bank(bank_path=JARGON_BANK):
    if not bank_path.exists():
        return {"entries": []}
    with open(bank_path, "r", encoding="utf-8") as f:
        return json.load(f)


def _build_substitution_table(bank, locale="fr", context="phantom-modes"):
    """Flatten the bank into a sorted list of (pattern, replacement) tuples.

    Longest variants first to avoid shadow-matching: "atlas vivant" must be
    matched before "atlas" alone would shadow it. Returns compiled regex
    patterns paired with their replacement string.
    """
    locale_key = "operator_en" if locale == "en" else "operator_fr"
    pairs = []
    for entry in bank.get("entries", []):
        if entry.get("context") and entry["context"] != context:
            continue
        replacement = entry.get(locale_key) or entry.get("operator_fr") or ""
        if not replacement:
            continue
        for variant in entry.get("internal", []):
            if not variant:
                continue
            pairs.append((variant, replacement))

    # Longest-first ordering on the source token
    pairs.sort(key=lambda p: len(p[0]), reverse=True)

    compiled = []
    case_flag = re.IGNORECASE
    for variant, replacement in pairs:
        # Escape regex metachars in the variant. Use a non-word-boundary
        # match when the variant contains punctuation (e.g. `validations[]`),
        # word boundary otherwise.
        escaped = re.escape(variant)
        if re.match(r"^[\w\s-]+$", variant):
            pattern = re.compile(rf"\b{escaped}\b", case_flag)
        else:
            pattern = re.compile(escaped, case_flag)
        compiled.append((pattern, replacement))
    return compiled


def _segment_protect_code(text):
    """Split text into segments, tagging code spans as protected.

    Returns list of tuples (segment, is_code). Code segments are passed
    through verbatim. Non-code segments receive substitution.
    """
    segments = []
    # First pass: extract fenced code blocks
    last_end = 0
    for match in CODE_FENCE_RE.finditer(text):
        if match.start() > last_end:
            segments.append((text[last_end:match.start()], False))
        segments.append((match.group(1), True))
        last_end = match.end()
    if last_end < len(text):
        segments.append((text[last_end:], False))

    # Second pass: within non-code segments, extract inline code
    refined = []
    for seg, is_code in segments:
        if is_code:
            refined.append((seg, True))
            continue
        inner_last = 0
        for match in INLINE_CODE_RE.finditer(seg):
            if match.start() > inner_last:
                refined.append((seg[inner_last:match.start()], False))
            refined.append((match.group(1), True))
            inner_last = match.end()
        if inner_last < len(seg):
            refined.append((seg[inner_last:], False))
    return refined


def apply_jargon_filter(text, locale="fr", bank=None, context="phantom-modes"):
    """Apply the jargon bank substitution on `text`.

    Args:
        text: input string (raw render output)
        locale: "fr" (default) or "en"
        bank: pre-loaded bank dict (optional, loads from disk if None)
        context: filter on entry.context (default "phantom-modes")

    Returns:
        filtered string with internal tokens replaced by operator-facing
        vocabulary, code blocks preserved verbatim.
    """
    if bank is None:
        bank = _load_bank()
    table = _build_substitution_table(bank, locale=locale, context=context)

    segments = _segment_protect_code(text)
    out_parts = []
    for seg, is_code in segments:
        if is_code:
            out_parts.append(seg)
            continue
        for pattern, replacement in table:
            seg = pattern.sub(replacement, seg)
        out_parts.append(seg)
    return "".join(out_parts)


def main():
    parser = argparse.ArgumentParser(description="v2.42 post-render jargon filter")
    parser.add_argument("--locale", choices=["fr", "en"], default="fr")
    parser.add_argument("--in", dest="infile", default=None, help="input file (defaults to stdin)")
    parser.add_argument("--out", dest="outfile", default=None, help="output file (defaults to stdout)")
    parser.add_argument("--context", default="phantom-modes", help="entry context filter")
    args = parser.parse_args()

    if args.infile:
        text = Path(args.infile).read_text(encoding="utf-8")
    else:
        text = sys.stdin.read()

    filtered = apply_jargon_filter(text, locale=args.locale, context=args.context)

    if args.outfile:
        Path(args.outfile).write_text(filtered, encoding="utf-8")
    else:
        sys.stdout.write(filtered)


if __name__ == "__main__":
    main()
